### ISSUE TITLE
Frontend#onError method has the same signature with BlocBase#onError of Bloc library

### ISSUE THREAD

**Issue by dtvtkien** [alphamikle/isolator#1]
I have an issue while using FrontEnd for [Bloc](https://pub.dev/packages/bloc) classes.
My code is:

```dart
class BookBloc extends Bloc<BookEvent, BookState> with Frontend<String> {
// Logic here...
}
```

The compiler will throw this error: ``'Frontend.onError' ('Future<void> Function(dynamic)') isn't a valid override of 'BlocBase.onError' ('void Function(Object, StackTrace)')``. Because your FrontEnd class has the same signature (method 's name) with BlocBase class.

How could I deal with this issue?

**Comment by alphamikle** [comment]
Hi, @dtvtkien. Unfortunately - for now, the only thing, that can be done to solve this issue - is a rename `onError` hook of `Frontend` mixin. I give advice to you - simply rename it in isolator's source code directory for now.

I will update isolator package in the next several days with the new major version v2 (which I writing right now), and also make a minor update for v1 with the renaming of `onError` hook. And thanks for your issue, initially I didn't think about possible name conflicts.

**Comment by dtvtkien** [comment]
Thanks for your fast response, @alphamikle!
You can find these conflicted method names [here](https://github.com/felangel/bloc/blob/35599cbe37973645e6d4c7466da33c0c9556ddd6/packages/bloc/lib/src/bloc.dart#L375). I also found ``Bloc#onEvent`` got the same issue!

**Comment by alphamikle** [comment]
Hello @dtvtkien! With the v2 of `isolator`, all conflicts were gone. Use for your pleasure!
